# alorenzetti 202008

# description ####
# this script will parse proteomics abundance data
# generated by Spectronaut software

# loading libs ####
source("./scripts/0_loadingLibs.R")

# loading files ####
file = "./data/Halo_WholeLysate_analysis_HaloIonLibraryVNG_merged_final_2018-04-07_SW100_Protein_Report_20200731.xls"
file2 = "./data/Halo_Ribo_analysis_HaloIonLibraryVNG_merged_final_2018-04-07_SW100_Protein_Report.xls"

# they will throw a warning saying
# cols were parsed as.character
# but we ll deal with that later
spectro1 = read_delim(file = file, delim = "\t")
spectro2 = read_delim(file = file2, delim = "\t")

# full join of both dataframes
spectro = full_join(spectro1, spectro2, by = "PG.ProteinAccessions")

# wrangling ####
# adjusting colnames
colnames(spectro)[-1] = sub("^\\[.* ", "", colnames(spectro)[-1])
colnames(spectro)[-1] = sub("^.*_?(BR[1-3])(TP[1-4]).*_.*_.*_(r0[1-3]).*$",
                            "\\2_\\1_\\3",
                            colnames(spectro)[-1],
                            perl = T)
colnames(spectro)[-1] = paste0(c(rep("lysate_", 36),
                                 rep("ribo_", 36)),
                               colnames(spectro)[-1])
colnames(spectro)[1] = "locus_tag"

# removing first entry line and pivoting
spectro = spectro[-1, ]

# warnings will be thrown due to
# missing entries ("Filtered" value)
spectro = spectro %>%
  mutate_at(.vars = vars(contains("BR")),
            .funs = as.numeric)

# pivoting data frame
# we will take run means and annotate number of runs used
# I would say using six (of nine) observations is fair enough
spectroLong = spectro %>%
  pivot_longer(cols = contains("BR"),
               names_to = c("libType", "timepoint", "bioRep", "run"),
               names_sep = "_",
               values_to = "abundance") %>% 
  group_by(locus_tag, libType, timepoint) %>% 
  summarise(nruns = 9 - sum(is.na(abundance)),
            mean_abundance = mean(abundance, na.rm = T),
            se_abundance = (sd(abundance, na.rm = T) / sqrt(nruns))) %>% 
  mutate(mean_abundance = case_when(is.nan(mean_abundance) ~ NA_real_,
                                    TRUE ~ as.numeric(mean_abundance)),
         se_abundance = case_when(is.nan(se_abundance) ~ NA_real_,
                                  TRUE ~ as.numeric(se_abundance))) %>% 
  ungroup() %>% 
  filter(nruns >= 6)

# in this moment, I will also remove #####
# protein groups containing more than
# one protein; but I should get back
# to it later to develop an approach that keeps
# only protein groups consisting of repetitions
# peptides shared between distinct protein
# will be ignored in the future
spectroLong = spectroLong %>% 
  filter(str_detect(string = locus_tag, pattern = ",", negate = T))

# using longer dataframe, I will
# create a wider version to be able
# to plot heat maps using ComplxHeatmaps
# and furthermore to unify it with
# RNA-Seq data
spectroWide = spectroLong %>% 
  select(-nruns) %>% 
  pivot_wider(names_from = c("libType", "timepoint"),
              names_sep = "_",
              values_from = c("mean_abundance", "se_abundance"))
colnames(spectroWide)[-1] = sub("abundance_", "abundance_protein_", colnames(spectroWide)[-1])

# adjusting locus_tags
# according to dictProd
# "VNG0212H"  "VNG0606G"  "VNG0779C"  "VNG0780H"  "VNG1585Cm"
# don't have a matching sequence in pfeiLocusTag
# those are going to be removed
spectroWide = left_join(spectroWide, dict, by = c("locus_tag" = "query_id"))

remove = spectroWide$locus_tag[is.na(spectroWide$subject_id) %>% which()]
spectroWide = spectroWide[!(spectroWide$locus_tag %in% remove),] %>% 
  mutate(locus_tag = subject_id) %>% 
  select(-subject_id)

# exploratory plots #####
# generating a heat map to check
# sample grouping
# defining heatmap col funct
colfunct = circlize::colorRamp2(breaks = c(0,3,6), colors = viridis(3))

# creating matrix
M = spectro[ ,-1] %>%
  select(-contains("ribo")) %>% 
  drop_na() %>%
  as.matrix() %>%
  log10()

# defining annotation colors
legendCols = list(
  timepoints = c("TP1" = "#E15759",
                 "TP2" = "#F28E2B",
                 "TP3" = "#4E79A7",
                 "TP4" = "#59A14F"),
  bioReps = c("BR1" = adjustcolor(col = "#76B7B2", alpha.f = 0.2),
              "BR2" = adjustcolor(col = "#76B7B2", alpha.f = 0.5),
              "BR3" = adjustcolor(col = "#76B7B2", alpha.f = 1)),
  runs = c("r01" = adjustcolor(col = "#EDC948", alpha.f = 0.2),
           "r02" = adjustcolor(col = "#EDC948", alpha.f = 0.5),
           "r03" = adjustcolor(col = "#EDC948", alpha.f = 1))
)

# defining annotations
tpannots = colnames(M) %>% str_replace(".*(TP[1-4]).*", "\\1")
brannots = colnames(M) %>% str_replace(".*(BR[1-3]).*", "\\1")
runannots = colnames(M) %>% str_replace(".*(r0[1-3])$", "\\1")

annot = HeatmapAnnotation(which = "col",
                          timepoints = anno_simple(tpannots,
                                                   col = legendCols$timepoints,
                                                   border = T),
                          bioReps = anno_simple(brannots,
                                                   col = legendCols$bioReps,
                                                   border = T),
                          runs = anno_simple(runannots,
                                                   col = legendCols$runs,
                                                   border = T),
                          annotation_label = c("Timepoint",
                                               "Bio. Replicate",
                                               "Run")
)

# defining legs
legs = list(
  timepoints = Legend(title = "Time Point",
                      at = legendCols$timepoints %>% names(),
                      legend_gp = gpar(fill = legendCols$timepoints %>% unname()),
                      border = "black"),
  bioReps = Legend(title = "Bio. Replicate",
                      at = legendCols$bioReps %>% names(),
                      legend_gp = gpar(fill = legendCols$bioReps %>% unname()),
                      border = "black"),
  runs = Legend(title = "Run",
                      at = legendCols$runs %>% names() %>% str_replace("r0", "R"),
                      legend_gp = gpar(fill = legendCols$runs %>% unname()),
                      border = "black")
)

# plotting heat map
ht = Heatmap(M, col = colfunct,
             top_annotation = annot,
             border = T,
             show_column_names = F,
             heatmap_legend_param = list(
               title = "Log10(Abundance)",
               border = T,
               direction = "horizontal"))

svglite("./plot/spectronautHeatmap.svg", width = 3, height = 4.5)
draw(ht,
     heatmap_legend_side = "bottom",
     annotation_legend_list = legs)
dev.off()

# plotting densities
# normalization doesnt seem necessary
# distributions are quite similar
# and look like poisson
# ggplot(spectroLong,
#        aes(x = log10(mean_abundance),
#            color = timepoint)) +
#   geom_density() +
#   facet_grid(~libType)
