# alorenzetti 202008

# description ####
# this script will perform PCA
# and plot the results
# using spectronaut results

# we are going to use a dataset ####
# generated by the previous script
# in this repo
spectroPCA = spectro %>% 
  select(-starts_with("ribo")) %>% 
  drop_na() %>% 
  transpose_tibble(locus_tag, id_col = "sample")

# adapted from:
# https://tbradley1013.github.io/2018/02/01/pca-in-a-tidy-verse-framework/
# creating a dataframe containing all pca info we need
dfpcaComplete = spectroPCA %>% 
  nest(data=everything()) %>% 
  dplyr::mutate(pca = map(data, ~ prcomp(.x %>% select(-sample), 
                                  center = T, scale = T)),
         pca_aug = map2(pca, data, ~augment(.x, data = .y)))

# computing the explained variance for
# each of the principal components
expVar = dfpcaComplete %>% 
  unnest(pca_aug) %>% 
  summarize_at(.vars = vars(contains(".fittedPC")), .funs = list(~var(.))) %>% 
  gather(key = pc, value = variance) %>% 
  mutate(var_exp = variance/sum(variance),
         cum_var_exp = cumsum(var_exp),
         pc = str_replace(pc, ".fitted", ""))

# preparing df to plot PCA
pcaAugDf = dfpcaComplete %>%
  unnest(pca_aug) %>%
  mutate(tp = str_replace(sample,".*(TP[1-4]).*", "\\1"),
         br = str_replace(sample,".*(BR[1-3]).*", "\\1"),
         run = str_replace(sample,".*r0([1-3])$", "R\\1"))

# finding top three loadings in PC1
dfpcaComplete$pca[[1]]$rotation[dfpcaComplete$pca[[1]]$rotation %>% .[,1] %>% order(decreasing = T),1] %>% head(3)

# finding bottom three loadings in PC1
dfpcaComplete$pca[[1]]$rotation[dfpcaComplete$pca[[1]]$rotation %>% .[,1] %>% order(decreasing = F),1] %>% head(3)

# plotting 2D scatter (alternative version to the 3D scatter)
spectronautplots$pca = pcaAugDf %>% 
  ggplot(aes(x=.fittedPC1, y=.fittedPC2, color = tp, shape = br)) +
  geom_point(alpha = 0.75) +
  xlab(paste0("PC1", " (", round(expVar$var_exp[1] * 100, digits = 2), "%)")) +
  ylab(paste0("PC2", " (", round(expVar$var_exp[2] * 100, digits = 2), "%)")) +
  scale_color_manual(values = c("TP1" = "#E15759",
                                "TP2" = "#F28E2B",
                                "TP3" = "#4E79A7",
                                "TP4" = "#59A14F"),
                     name="Time Point") +
  scale_shape_discrete(name="Bio. Replicate") +
  guides(colour = guide_legend(order = 1), 
         shape = guide_legend(order = 2)) +
  ggtitle("A")

# arranging panel of pca and heatmap
spectronautplots$panel = ggarrange(plotlist = list(spectronautplots$pca,
                                                   spectronautplots$drawnht),
                                   widths = c(1.5,1))
# saving 
svglite(file = "plot/figureSpectronaut.svg",
        width = 7, height = 5)
spectronautplots$panel
dev.off()

png(file = "plot/figureSpectronaut.png",
        width = 7, height = 5, units = "in", res = 600)
spectronautplots$panel
dev.off()

# plotting explained variance
cumuvarplot = expVar %>%
  pivot_longer(cols = contains("exp"),
               values_to = "var",
               names_to = "key") %>%
  mutate(key = case_when(key == "cum_var_exp" ~ "Cumulative Explained Variance",
                         key == "var_exp" ~ "Explained Variance",
                         TRUE ~ as.character(key))) %>% 
  ggplot(aes(x = factor(pc,levels = pc %>% unique() %>% str_sort(numeric = T)),
             y = var,
             group = key)) +
  geom_point() +
  geom_line() +
  facet_wrap(~key, scales = "free_y") +
  lims(y = c(0, 1)) +
  labs(y = "Variance",
       x = "Principal Components") +
  theme(axis.text.x = element_text(angle = 90))

# saving previous plot
ggsave("./plot/spectronautCumuvarplot.svg",
       plot=cumuvarplot,
       width = 8.5, height = 5)

ggsave("./plot/spectronautCumuvarplot.png",
       plot=cumuvarplot,
       width = 8.5, height = 5)
